name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12

      - name: Install server dependencies
        run: |
          sudo apt-get install libpq-dev
          python -m pip install --upgrade pip
          pip install poetry
          source $HOME/.poetry/env
          poetry install

      - name: Build Package
        run: poetry build

      - name: Saving package
        uses: actions/upload-artifact@v2
        with:
          name: data-pyetl
          path: dist/
  publish:
    name: Publish on Pypi
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12

      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
