name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          cd data-pyetl/ && poetry install
      - name: Build package
        run: |
          source $HOME/.poetry/env
          poetry build

      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.10
        with:
          python_version: "3.8.12"
          poetry_version: "==1.1.13" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
          allow_poetry_pre_release: "yes"
          ignore_dev_requirements: "yes"
