name: Upload Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
      - uses: actions/checkout@v2
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
