name: Upload Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - "v.*.*"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.10
        run: cd data-pyetl/
        with:
          python_version: "3.8.12"
          poetry_version: "==1.1.13" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
          allow_poetry_pre_release: "yes"
          ignore_dev_requirements: "yes"
