# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
      - develop
      - release
      - "feature/*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.17"
      - name: Install dependencies and Test
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install libpq-dev
          pip install poetry
          source $HOME/.poetry/env
          poetry install
          poetry run pytest --cov=data_pyetl/ --cov-report xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
